# Generated by Django 2.2.16 on 2020-10-08 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_customtext_sdfseage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='sdfseage',
        ),
    ]
